
* Overview  
fyj-mode is a minor mode for playing background music. Currently, I
only implement the basic background music playing function. When time
is permitted, I'll try to implement more functions:

** TODO-List [1/2]
   - [X] trigger playing music one by one only by one time. 
     Currently, you must trigger the song  playing everytime when the
     previous song playing is over.
   - [ ] more accurate music playing control.

* Usage
  
** Customized configuration. 
   I have defined two virables which you must set first. 
   1. =fyj-player=
      beacause we need a music player backend to actually to do the
      music playing work, so you need specify
      one, Suggested values are:
      - *mplayer*  using mplayer as the backend
      - *cvlc*     using vlc as the backend"
   2. =fyj-playlistdir=
      the directory where your music files stored. Currently, I only
      select mp3 file.

** add the mode to your emacs configuration
   to use this mode, you only need to put this file to your emacs load path,
   then add the following code in your emacs init script:
   #+BEGIN_SRC emacs-lisp
     (require 'fyj-mode)
     (global-set-key (kbd "<f5>") 'global-fyj-mode)   
   #+END_SRC
   
   as you can see, I bind <F5> as the key to toggle the music
   player. Of course you can choose any other key bindings at your
   will. 
